//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;

//using Android.App;
//using Android.Content;
//using Android.OS;
//using Android.Runtime;
//using Android.Util;
//using Android.Views;
//using Android.Widget;
//using TestShopApp1.Adapters;

//namespace TestShopApp1.Fragments {
//    public class FavoriteHotDogFragment : BaseFragment {

//        public override void OnCreate(Bundle savedInstanceState) {
//            base.OnCreate(savedInstanceState);

//            // Create your fragment here
//        }

//        /// <summary>
//        /// Called when the activity that hosts this fragment is ready.
//        /// </summary>
//        /// <param name="savedInstanceState"></param>
//        public override void OnActivityCreated(Bundle savedInstanceState) {
//            base.OnActivityCreated(savedInstanceState);

//            //FindViews();
//            //HandleEvents();

//            //hotDogs = hotDogDataService.GetFavoriteHotDogs();
//            //listView.Adapter = new ItemListAdapter(this.Activity, hotDogs);
//        }

//        public override View OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
            
//            // Use this to return your custom view for this Fragment
//            return inflater.Inflate(Resource.Layout.favoriteHotDogFragment, container, false);

//            // this is autogenerated code
//            //return base.OnCreateView(inflater, container, savedInstanceState);
//        }
//    }
//}